Repository kaizen-ai/kaizenflow, pull requests merged in 2023-08, with the labels that each got.

#476 Expose realtime_client_example1 issue #475
  im_v2/ccxt/data/client/ccxt_clients_example.py
  im_v2/ccxt/data/client/test/test_ccxt_clients.py
Labels: PR_for_integrators

#349 SorrTask229_Programmatically_invite_people_to_GitHub_Part2
  dev_scripts/invite_github_collaborator.py
Labels: PR_for_integrators

#486 SorrTask485_Unit_test_plot_spectrum
  core/plotting/notebooks/gallery_notebook.ipynb
  core/plotting/notebooks/gallery_notebook.py
  core/plotting/test/test_plots.py
Labels: PR_for_integrators

#495 improve multiindex_df_info() and add unittest
  helpers/hpandas.py
  helpers/test/test_hpandas.py
Labels: PR_for_reviewers

#424 Sorr task409 unit test plot timeseries distribution
  core/plotting/misc_plotting.py
  core/plotting/notebooks/gallery_notebook.ipynb
  core/plotting/notebooks/gallery_notebook.py
  core/plotting/test/test_plots.py
Labels: PR_for_integrators

#453 SorrTask447 Convert Telegram GDoc to MD
  README.md
  docs/Telegram.md
Labels: PR_for_integrators

#471 change minute to hour and modify unit test #469
  im_v2/common/data/client/historical_pq_clients_example.py
  im_v2/common/data/client/test/test_historical_pq_clients.py
Labels: PR_for_integrators

#505 Sorr Task493 Rename gsheets name
  linkedin/notebooks/process_profile_export.ipynb
  linkedin/notebooks/process_profile_export.py
  linkedin/notebooks/process_search_export.ipynb
  linkedin/notebooks/process_search_export.py
Labels: PR_for_reviewers

#432 #432 Mail List gDoc to MD #412
  README.md
  docs/Email.md
Labels: PR_for_integrators

#386 CmTask351_Improvement_to_the_encryption_flow_testing_part
  dev_scripts/encrypt_model.py
Labels: PR_for_authors

#517 SorrIssue510_Make_a_documentation_for_replace_text.py
  README.md
  docs/Codebase_clean_up_scripts.md
Labels: PR_for_reviewers

#482 Gallery notebook test_rets_signal_analysis
  core/plotting/notebooks/gallery_notebook.ipynb
  core/plotting/notebooks/gallery_notebook.py
  core/plotting/test/test_plots.py
Labels: PR_for_integrators

#515 Sorr Task 487 PB results to local storage
  linkedin/notebooks/download_result_csv.ipynb
  linkedin/notebooks/download_result_csv.py
  linkedin/phantom_api/__init__.py
  linkedin/phantom_api/phantombuster_api.py
Labels: PR_for_reviewers

#521 SorrTask501_Fix_each_cause_of_issues_when_running_regressions
  dataflow/model/test/test_run_notebooks.py
  helpers/lib_tasks_pytest.py
  helpers/test/test_git.py
  helpers/test/test_lib_tasks.py
  helpers/test/test_lib_tasks_docker.py
  helpers/test/test_lib_tasks_pytest.py
Labels: PR_for_reviewers

#524 SorrTask518_Add_mocking_to_isolate_the_deps_for_ck_dev_servers
  helpers/test/test_lib_tasks.py
  helpers/test/test_lib_tasks_gh.py
  helpers/test/test_lib_tasks_pytest.py
  optimizer/test/test_single_period_optimization.py
  tasks.py
Labels: PR_for_reviewers

#527 SorrTask518_Add_mocking_to_isolate_the_deps_for_ck_dev_servers_2
  helpers/test/test_lib_tasks.py
  helpers/test/test_lib_tasks_gh.py
  helpers/test/test_lib_tasks_pytest.py
Labels: PR_for_reviewers

#519 SorrTask-513-clean-up-gsheet_into_pandas-doc
  README.md
  docs/Gsheet_into_pandas.md
Labels: PR_for_integrators

#520 Sorr task492 expose gallery notebook config
  core/plotting/notebooks/gallery_notebook.ipynb
  core/plotting/notebooks/gallery_notebook.py
  core/plotting/test/test_gallery_notebook.py
  docs/Unit_tests.md
  docs/Unit_tests_figs/image_1.png
  docs/Unit_tests_figs/image_2.png
  docs/Unit_tests_figs/image_3.png
  docs/Unit_tests_figs/image_4.png
Labels: PR_for_integrators

#449 SorrTask419_Glossary_gDoc_to_MD
  README.md
  docs/Glossary.md
Labels: PR_for_integrators

#534 SorrTask511_Clean-up_documentation
  README.md
  docs/Arbitrage_papers.md
  docs/DataFlow.md
  docs/DataPull.md
  docs/How_to_integrate_repos.md
Labels: PR_for_integrators

#530 SorrTask529_Generalize_the_switch_to_take_a_marker
  dataflow/core/nodes/test/test_volatility_models.py
  dataflow/model/test/test_run_notebooks.py
  helpers/hcache.py
  helpers/lib_tasks_pytest.py
  helpers/test/test_git.py
  helpers/test/test_hpandas.py
  helpers/test/test_hparquet.py
  helpers/test/test_hs3.py
  helpers/test/test_hsecrets.py
  helpers/test/test_lib_tasks.py
  helpers/test/test_lib_tasks_docker.py
  helpers/test/test_s3.py
  helpers/test/test_unit_test.py
  im/ib/data/load/test/test_file_path_generator.py
  im/ib/data/load/test/test_s3_data_loader.py
  im/kibot/data/load/test/test_s3_data_loader.py
  im/kibot/metadata/test/test_kibot_metadata.py
  im_v2/ccxt/data/client/test/test_ccxt_clients.py
  im_v2/ccxt/db/test/test_archive_db_data_to_s3.py
  im_v2/common/data/extract/test/test_extract_utils.py
  im_v2/ig/data/client/test/test_ig_historical_pq_by_date_taq_bar_client.py
  im_v2/ig/data/client/test/test_taq_bars_utils.py
  im_v2/talos/data/client/test/test_talos_clients.py
  market_data/test/test_real_time_market_data.py
Labels: PR_for_reviewers

#525 Sorr Task496 refine google sheets flow
  linkedin/google_api/google_drive_api.py
  linkedin/notebooks/create_gsheets_and_fetch_result_csv.ipynb
  linkedin/notebooks/create_gsheets_and_fetch_result_csv.py
  linkedin/notebooks/download_result_csv.ipynb
  linkedin/notebooks/download_result_csv.py
  linkedin/notebooks/process_profile_export.ipynb
  linkedin/notebooks/process_profile_export.py
  linkedin/notebooks/process_search_export.ipynb
  linkedin/notebooks/process_search_export.py
Labels: PR_for_reviewers

#452 Sorr issue428 tools profiling gdoc to md
  README.md
  docs/Profiling.md
  docs/Profiling_figs/image1.png
  docs/Profiling_figs/image2.png
Labels: PR_for_integrators

#543 SorrTask 481 Unit test plot_cols()
  core/plotting/notebooks/gallery_notebook.ipynb
  core/plotting/notebooks/gallery_notebook.py
  core/plotting/test/test_plots.py
Labels: PR_for_integrators

#545 Sorr Task468 remove unused functions from dataflow
  dataflow/system/system_builder_utils.py
Labels: PR_for_integrators

#499 Sorr task462 unit test plot performance
  core/plotting/notebooks/gallery_notebook.ipynb
  core/plotting/notebooks/gallery_notebook.py
  dataflow/model/test/test_model_plotter.py
Labels: PR_for_integrators

#550 Sorr task483 unit test plot autocorrelation
  core/plotting/test/test_plots.py
Labels: PR_for_reviewers
