Repository kaizen-ai/kaizenflow, pull requests merged in 2023-06, with the labels that each got.

#295 SorrTask64: implement First review doc follow-ups
  docs/First_review_process.md
Labels: PR_for_integrators

#305 Sorr task64 update first review doc
  docs/First_review_process.md
Labels: PR_for_integrators

#269 Sorrtask154 supply/demand follow ups
  defi/tulip/implementation/optimize.py
  defi/tulip/implementation/order.py
  defi/tulip/implementation/supply_demand.py
  defi/tulip/notebooks/SorrTask139_Create_some_pathological_cases_for_supply_demand_curve.ipynb
  defi/tulip/notebooks/SorrTask139_Create_some_pathological_cases_for_supply_demand_curve.py
  defi/tulip/notebooks/SorrTask154_Create_linear_supply_demand_curves_using_orders.ipynb
  defi/tulip/notebooks/SorrTask154_Create_linear_supply_demand_curves_using_orders.py
Labels: PR_for_integrators

#290 SorrTask261: Create matching service
  defi/tulip/implementation/order_matching.py
  defi/tulip/services/matching/__init__.py
  defi/tulip/services/matching/order_matcher.py
  defi/tulip/test/test_order_matching.py
Labels: PR_for_reviewers

#284 Issue256 Updated the docs folder with Jupyter_NB_Best_practices
  docs/Jupyter_notebook_best_practices.md
  docs/README.md
Labels: PR_for_integrators

#309 Sorr task64 update coding style doc
  docs/Coding_Style_Guide.md
Labels: PR_for_integrators

#306 Sorr task64 update documentation guidelines
  docs/Documentation_about_guidelines.md
Labels: PR_for_integrators

#312 SorrTask64: Lint General rules of collab
  docs/General_rules_of_collaboration.md
Labels: PR_for_integrators

#249 Issue109 add unit test using get random order
  defi/tulip/test/test_order_matching.py
Labels: PR_for_integrators

#316 SorrIssue315 Update Morning Email
  docs/General_rules_of_collaboration.md
  docs/Morning_Emails_Figs/1_Visits.png
  docs/Morning_Emails_Figs/2_Settings.png
  docs/Morning_Emails_Figs/3_Request.png
  docs/Morning_Emails_Figs/image.png
Labels: PR_for_reviewers

#320 SorrTask319: Refine convert_gdoc_to_markdown.sh
  dev_scripts/convert_docx_to_markdown.sh
  dev_scripts/lint_md.sh
Labels: PR_for_integrators

#331 Sorrtask298 rename get docker cmd to get docker run cmd
  dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
  im_v2/im_lib_tasks.py
  im_v2/test/test_im_lib_tasks.py
  oms/oms_lib_tasks.py
Labels: PR_for_integrators

#327 SorrTask240 create a function that executes order at specified price
  defi/tulip/implementation/order.py
  defi/tulip/test/test_order.py
Labels: PR_for_integrators

#313 SorrTask270_Encryption_flow_for_models
  dev_scripts/encrypt_model.py
Labels: PR_for_integrators

#317 SorrIssue244 CCXT timestamp representation unit test
  .gitignore
  im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
Labels: PR_for_integrators

#335 SorrIssue328 Convert Type Hints gDoc to Markdown
  docs/Type_hints.md
Labels: PR_for_integrators

#343 SorrIssue342 Misc improvements to the on boarding flow
  docs/How_to_organize_your_work.md
  docs/Quick_start_for_developing.md
Labels: PR_for_integrators

#324 SorrTask64: Update Git workflow doc with gh_issue_title
  docs/Git_workflow_and_best_practices.md
Labels: PR_for_integrators

#307 300 converting unit test gdoc to markdown
  dev_scripts/setenv_amp.sh
  docs/README.md
  docs/Unit_tests.md
  docs/unit_tests_figs/image_1.png
  docs/unit_tests_figs/image_2.png
  docs/unit_tests_figs/image_3.png
  docs/unit_tests_figs/image_4.png
Labels: PR_for_integrators

#350 SorrTask258_Replace_pytest_raises_with_self_assertraises_new
  dev_scripts/cleanup_scripts/SorrTask258_Replace_pytest_raises_with_self_assertraises.sh
Labels: PR_for_integrators

#347 SorrTask 257 Convert Docker Google Doc to Markdown
  docs/Docker.md
  docs/Docker_figs/image1.png
  docs/Docker_figs/image2.png
  docs/README.md
Labels: PR_for_integrators

#357 Update General_rules_of_collaboration.md
  docs/General_rules_of_collaboration.md
Labels: PR_for_integrators

#344 SorrTask332_Convert_Code_Review_gDoc_to_Markdown
  docs/Code_review.md
  docs/README.md
Labels: PR_for_reviewers

#338 Create Development_workflow.md
  docs/Development_workflow.md
  docs/README.md
Labels: PR_for_integrators

#363 SorrTask354_Unit_test_get_function_from_string1
  helpers/test/test_hintrospection.py
Labels: PR_for_integrators

#371 SorrTask370 invoke tasks doesn't work from sorrentum
  helpers/lib_tasks_docker.py
Labels: PR_for_reviewers, Blocking

#372 Create Scrum_methodology.md
  docs/Scrum_methodology.md
Labels: PR_for_reviewers
