Repository kaizen-ai/kaizenflow, pull requests merged in 2024-05, with the labels that each got.

#883 SorrTask786 Unit test for split_positive_and_negative_parts()
  core/signal_processing/test/test_misc_transformations.py
Labels: PR_for_integrators

#901 SorrTask-891 Unit tests for compute epoch function
  core/finance/prediction_processing.py
  core/finance/test/test_prediction_processing.py
Labels: PR_for_reviewers

#907 SorTask903 Unit test convert_seconds_to_pandas_minutes()
  helpers/test/test_hdatetime.py
Labels: PR_for_integrators

#982 Issue-785 Draft code for unit tests of normalize function
  core/signal_processing/test/test_misc_transformations.py
Labels: PR_for_reviewers

#995 CmampTask8340_GitHub_actions_and_bashing_into_docker_container_is_failing
  .github/gh_requirements.txt
  dev_scripts/client_setup/requirements.txt
  docs/dev_tools/thin_env/all.gh_and_thin_env_requirements.reference.md
  helpers/test/test_hparquet.py
Labels: PR_for_reviewers

#1006 SorrTask997_sota_baseline
  research_amp/sports_prediction/sota_baseline_double_poisson.ipynb
  research_amp/sports_prediction/sota_baseline_double_poisson.py
Labels: bug

#1013 Unit test compute_bar_start_timestamps()
  core/finance/test/test_prediction_processing.py
Labels: PR_for_integrators
